- url: https://www.w3.org/TR/beacon/
  title: Beacon
- url: https://www.w3.org/TR/clipboard-apis/
  title: Clipboard
- url: https://compat.spec.whatwg.org/
  title: Compatibility
  deprecated: true
- url: https://console.spec.whatwg.org/
  title: Console
- url: https://www.w3.org/TR/credential-management-1/
  title: Credential Management
- url: https://www.w3.org/TR/css-animations-1/
  title: CSS Animations
- url: https://www.w3.org/TR/css-backgrounds-3/
  title: CSS Backgrounds and Borders
- url: https://drafts.csswg.org/css-backgrounds-4/
  title: CSS Backgrounds and Borders Level 4
- url: https://www.w3.org/TR/css-ui-3/
  title: CSS Basic User Interface
- url: https://www.w3.org/TR/css-align-3/
  title: CSS Box Alignment
- url: https://www.w3.org/TR/css-cascade-3/
  title: CSS Cascading and Inheritance
- url: https://www.w3.org/TR/css-color-3/
  title: CSS Color
- url: https://drafts.csswg.org/css-conditional-3/
  title: CSS Conditional Rules
- url: https://www.w3.org/TR/fill-stroke-3/
  title: CSS Fill and Stroke
- url: https://www.w3.org/TR/css-flexbox-1/
  title: CSS Flexible Box Layout
- url: https://www.w3.org/TR/css-fonts-3/
  title: CSS Fonts
- url: https://www.w3.org/TR/css-break-3/
  title: CSS Fragmentation
- url: https://www.w3.org/TR/css-grid-1/
  title: CSS Grid Layout
- url: https://drafts.csswg.org/css-images-3/
  title: CSS Images
- url: https://www.w3.org/TR/css-inline-3/
  title: CSS Inline Layout
- url: https://www.w3.org/TR/css-logical-1/
  title: CSS Logical Properties and Values
- url: https://drafts.fxtf.org/css-masking-1/
  title: CSS Masking
- url: https://www.w3.org/TR/css-multicol-1/
  title: CSS Multi-column Layout
- url: https://drafts.csswg.org/cssom/
  title: CSS Object Model
#- url: https://drafts.csswg.org/cssom-view/
#  title: CSSOM View
- url: https://www.w3.org/TR/css-overflow-3/
  title: CSS Overflow
- url: https://www.w3.org/TR/css-overscroll-1/
  title: CSS Overscroll Behavior
- url: https://www.w3.org/TR/css-ruby-1/
  title: CSS Ruby Layout
- url: https://drafts.csswg.org/css-scroll-anchoring/
  title: CSS Scroll Anchoring
- url: https://www.w3.org/TR/css-text-3/
  title: CSS Text
- url: https://www.w3.org/TR/css-text-decor-3/
  title: CSS Text Decoration
- url: https://www.w3.org/TR/css-transitions-1/
  title: CSS Transitions
- url: https://www.w3.org/TR/css-transforms-1/
  title: CSS Transforms
- url: https://drafts.csswg.org/css-transforms-2/
  title: CSS Transforms Level 2
- url: https://www.w3.org/TR/css-will-change/
  title: CSS Will Change
- url: https://www.w3.org/TR/css-writing-modes-3/
  title: CSS Writing Modes
- url: https://www.w3.org/TR/CSS22/box.html
  title: CSS2 Box
- url: https://www.w3.org/TR/CSS22/generate.html
  title: CSS2 Generated content
- url: https://www.w3.org/TR/CSS22/page.html
  title: CSS2 Paged media
- url: https://www.w3.org/TR/CSS22/tables.html
  title: CSS2 Tables
- url: https://www.w3.org/TR/CSS22/text.html
  title: CSS2 Text
- url: https://www.w3.org/TR/CSS22/visufx.html
  title: CSS2 Visual effect
- url: https://www.w3.org/TR/CSS22/visuren.html
  title: CSS2 Visual formatting
- url: https://www.w3.org/TR/CSS22/visudet.html
  title: CSS2 Visual formatting details
- url: https://w3c.github.io/deviceorientation/
  title: DeviceOrientation Event
- url: https://dom.spec.whatwg.org/
  title: DOM
- url: https://w3c.github.io/DOM-Parsing/
  title: DOM Parsing and Serialization
- url: https://encoding.spec.whatwg.org/
  title: Encoding
- url: https://www.w3.org/TR/encrypted-media/
  title: Encrypted Media Extensions
- url: https://fetch.spec.whatwg.org/
  title: Fetch
- url: https://w3c.github.io/FileAPI/
  title: File
- url: https://www.w3.org/TR/filter-effects-1/
  title: Filter Effects
- url: https://fullscreen.spec.whatwg.org/
  title: Fullscreen
- url: https://www.w3.org/TR/gamepad/
  title: Gamepad
- url: https://w3c.github.io/gamepad/extensions.html
  title: Gamepad Extensions
- url: https://w3c.github.io/geolocation-api/
  title: Geolocation
- url: https://www.w3.org/TR/geometry-1/
  title: Geometry Interfaces
- url: https://www.w3.org/TR/hr-time-2/
  title: High Resolution Time
- url: https://html.spec.whatwg.org/
  title: HTML
- url: https://w3c.github.io/webrtc-identity/
  title: Identity for WebRTC
- url: https://www.w3.org/TR/IndexedDB-2/
  title: Indexed Database
- url: https://w3c.github.io/IntersectionObserver/
  title: Intersection Observer
- url: https://w3c.github.io/mediacapture-main/
  title: Media Capture and Streams
- url: https://w3c.github.io/media-playback-quality/
  title: Media Playback Quality
- url: https://www.w3.org/TR/media-source/
  title: Media Source Extensions
- url: https://w3c.github.io/navigation-timing/
  title: Navigation Timing
- url: https://notifications.spec.whatwg.org/
  title: Notifications
- url: https://w3c.github.io/page-visibility/
  title: Page Visibility
- url: https://w3c.github.io/performance-timeline/
  title: Performance Timeline
- url: https://www.w3.org/TR/permissions/
  title: Permissions
- url: https://www.w3.org/TR/pointerevents2/
  title: Pointer Events
- url: https://www.w3.org/TR/pointerlock-2/
  title: Pointer Lock
- url: https://www.w3.org/TR/push-api/
  title: Push
- url: https://www.w3.org/TR/referrer-policy/
  title: Referrer Policy
- url: https://w3c.github.io/resource-timing/
  title: Resource Timing
- url: https://www.w3.org/TR/screen-orientation/
  title: Screen Orientation
- url: https://www.w3.org/TR/secure-contexts/
  title: Secure Contexts
- url: https://www.w3.org/TR/selection-api/
  title: Selection
- url: https://w3c.github.io/ServiceWorker/
  title: Service Workers
- url: https://storage.spec.whatwg.org/
  title: Storage
- url: https://streams.spec.whatwg.org/
  title: Streams
- url: https://www.w3.org/TR/SVG2/idl.html
  title: SVG
- url: https://w3c.github.io/touch-events/
  title: Touch Events
- url: https://www.w3.org/TR/uievents/
  title: UI Events
- url: https://url.spec.whatwg.org/
  title: URL
- url: https://www.w3.org/TR/user-timing-2/
  title: User Timing
- url: https://www.w3.org/TR/vibration/
  title: Vibration
- url: https://www.w3.org/TR/web-animations-1/
  title: Web Animations
- url: https://www.w3.org/TR/wasm-js-api-1/
  title: WebAssembly JavaScript Interface
- url: https://www.w3.org/TR/wasm-web-api-1/
  title: WebAssembly Web API
- url: https://webaudio.github.io/web-audio-api/
  title: Web Audio
- url: https://w3c.github.io/webauthn/
  title: Web Authentication
- url: https://wicg.github.io/background-sync/spec/
  title: Web Background Synchronization
- url: https://w3c.github.io/webcrypto/
  title: Web Cryptography
- url: https://www.w3.org/TR/webdriver1/
  title: WebDriver
- url: https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl
  title: WebGL 1
- url: https://www.khronos.org/registry/webgl/specs/latest/2.0/webgl2.idl
  title: WebGL 2
- url: https://www.khronos.org/registry/webgl/extensions/ANGLE_instanced_arrays/
  title: WebGL ANGLE_instanced_arrays
- url: https://www.khronos.org/registry/webgl/extensions/EXT_blend_minmax/
  title: WebGL EXT_blend_minmax
- url: https://www.khronos.org/registry/webgl/extensions/EXT_frag_depth/
  title: WebGL EXT_frag_depth
- url: https://www.khronos.org/registry/webgl/extensions/EXT_shader_texture_lod/
  title: WebGL EXT_shader_texture_lod
- url: https://www.khronos.org/registry/webgl/extensions/EXT_texture_filter_anisotropic/
  title: WebGL EXT_texture_filter_anisotropic
- url: https://www.khronos.org/registry/webgl/extensions/EXT_sRGB/
  title: WebGL EXT_sRGB
- url: https://www.khronos.org/registry/webgl/extensions/OES_element_index_uint/
  title: WebGL OES_element_index_uint
- url: https://www.khronos.org/registry/webgl/extensions/OES_standard_derivatives/
  title: WebGL OES_standard_derivatives
- url: https://www.khronos.org/registry/webgl/extensions/OES_texture_half_float/
  title: WebGL OES_texture_half_float
- url: https://www.khronos.org/registry/webgl/extensions/OES_texture_half_float_linear/
  title: WebGL OES_texture_half_float_linear
- url: https://www.khronos.org/registry/webgl/extensions/OES_texture_float/
  title: WebGL OES_texture_float
- url: https://www.khronos.org/registry/webgl/extensions/OES_texture_float_linear/
  title: WebGL OES_texture_float_linear
- url: https://www.khronos.org/registry/webgl/extensions/OES_vertex_array_object/
  title: WebGL OES_vertex_array_object
- url: https://www.khronos.org/registry/webgl/extensions/WEBGL_color_buffer_float/
  title: WebGL WEBGL_color_buffer_float
- url: https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_astc/
  title: WebGL WEBGL_compressed_texture_astc
- url: https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_s3tc/
  title: WebGL WEBGL_compressed_texture_s3tc
- url: https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_s3tc_srgb/
  title: WebGL WEBGL_compressed_texture_s3tc_srgb
- url: https://www.khronos.org/registry/webgl/extensions/WEBGL_debug_renderer_info/
  title: WebGL WEBGL_debug_renderer_info
- url: https://www.khronos.org/registry/webgl/extensions/WEBGL_debug_shaders/
  title: WebGL WEBGL_debug_shaders
- url: https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/
  title: WebGL WEBGL_depth_texture
- url: https://www.khronos.org/registry/webgl/extensions/WEBGL_draw_buffers/
  title: WebGL WEBGL_draw_buffers
- url: https://www.khronos.org/registry/webgl/extensions/WEBGL_lose_context/
  title: WebGL WEBGL_lose_context
- url: https://heycam.github.io/webidl/
  title: Web IDL
- url: https://w3c.github.io/webrtc-pc/
  title: WebRTC
- url: https://www.w3.org/TR/web-share/
  title: Web Share
- url: https://wicg.github.io/speech-api/
  title: Web Speech API
- url: https://wicg.github.io/visual-viewport/
  title: Web VisualViewport API
- url: https://www.w3.org/TR/webvtt1/
  title: WebVTT
- url: https://drafts.css-houdini.org/worklets/
  title: Worklets
- url: https://xhr.spec.whatwg.org/
  title: XMLHttpRequest
- url: https://www.w3.org/TR/css-pseudo-4/
  title: CSS Pseudo-Elements Module
- url: https://mathml-refresh.github.io/mathml-core/
  title: MathML Core
- url: https://w3c.github.io/aria/
  title: ARIA